// Book codes match the eBible.org VPL file (resources/bible/vie1934.txt.gz). [code, name, abbreviation]
export const BOOKS: [string, string, string][] = [
  ['GEN', 'Sáng Thế Ký', 'Sáng'],
  ['EXO', 'Xuất Ê-díp-tô Ký', 'Xuất'],
  ['LEV', 'Lê-vi Ký', 'Lê'],
  ['NUM', 'Dân Số Ký', 'Dân'],
  ['DEU', 'Phục Truyền Luật Lệ Ký', 'Phục'],
  ['JOS', 'Giô-suê', 'Giôs'],
  ['JDG', 'Các Quan Xét', 'Quan'],
  ['RUT', 'Ru-tơ', 'Ru'],
  ['1SA', '1 Sa-mu-ên', '1Sa'],
  ['2SA', '2 Sa-mu-ên', '2Sa'],
  ['1KI', '1 Các Vua', '1Vua'],
  ['2KI', '2 Các Vua', '2Vua'],
  ['1CH', '1 Sử Ký', '1Sử'],
  ['2CH', '2 Sử Ký', '2Sử'],
  ['EZR', 'E-xơ-ra', 'Exr'],
  ['NEH', 'Nê-hê-mi', 'Nê'],
  ['EST', 'Ê-xơ-tê', 'Êxt'],
  ['JOB', 'Gióp', 'Gióp'],
  ['PSA', 'Thi Thiên', 'Thi'],
  ['PRO', 'Châm Ngôn', 'Châm'],
  ['ECC', 'Truyền Đạo', 'Truyền'],
  ['SOL', 'Nhã Ca', 'Nhã'],
  ['ISA', 'Ê-sai', 'Ês'],
  ['JER', 'Giê-rê-mi', 'Giê'],
  ['LAM', 'Ca Thương', 'Ca'],
  ['EZE', 'Ê-xê-chi-ên', 'Êxê'],
  ['DAN', 'Đa-ni-ên', 'Đa'],
  ['HOS', 'Ô-sê', 'Ôs'],
  ['JOE', 'Giô-ên', 'Giôên'],
  ['AMO', 'A-mốt', 'Am'],
  ['OBA', 'Áp-đia', 'Áp'],
  ['JON', 'Giô-na', 'Giôn'],
  ['MIC', 'Mi-chê', 'Mi'],
  ['NAH', 'Na-hum', 'Na'],
  ['HAB', 'Ha-ba-cúc', 'Ha'],
  ['ZEP', 'Sô-phô-ni', 'Sô'],
  ['HAG', 'A-ghê', 'Ag'],
  ['ZEC', 'Xa-cha-ri', 'Xa'],
  ['MAL', 'Ma-la-chi', 'Mal'],
  ['MAT', 'Ma-thi-ơ', 'Mat'],
  ['MAR', 'Mác', 'Mác'],
  ['LUK', 'Lu-ca', 'Lu'],
  ['JOH', 'Giăng', 'Gi'],
  ['ACT', 'Công Vụ Các Sứ Đồ', 'Công'],
  ['ROM', 'Rô-ma', 'Rô'],
  ['1CO', '1 Cô-rinh-tô', '1Cô'],
  ['2CO', '2 Cô-rinh-tô', '2Cô'],
  ['GAL', 'Ga-la-ti', 'Ga'],
  ['EPH', 'Ê-phê-sô', 'Êph'],
  ['PHI', 'Phi-líp', 'Phi'],
  ['COL', 'Cô-lô-se', 'Côl'],
  ['1TH', '1 Tê-sa-lô-ni-ca', '1Tê'],
  ['2TH', '2 Tê-sa-lô-ni-ca', '2Tê'],
  ['1TI', '1 Ti-mô-thê', '1Ti'],
  ['2TI', '2 Ti-mô-thê', '2Ti'],
  ['TIT', 'Tít', 'Tít'],
  ['PHM', 'Phi-lê-môn', 'Phlm'],
  ['HEB', 'Hê-bơ-rơ', 'Hê'],
  ['JAM', 'Gia-cơ', 'Gia'],
  ['1PE', '1 Phi-e-rơ', '1Phi'],
  ['2PE', '2 Phi-e-rơ', '2Phi'],
  ['1JO', '1 Giăng', '1Gi'],
  ['2JO', '2 Giăng', '2Gi'],
  ['3JO', '3 Giăng', '3Gi'],
  ['JUD', 'Giu-đe', 'Giu'],
  ['REV', 'Khải Huyền', 'Khải']
]
